namespace:
  name: staging

service:
  port: 8111
  type: ClusterIP

replicaCount: 1

image:
  repository: nginx
  tag: 1.18.0
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 50m
    memory: 128Mi

configmap:
  data: "version: 1.18.0"
