namespace:
  name: prod

service:
  port: 80
  type: ClusterIP

replicaCount: 2

image:
  repository: nginx
  tag: 1.17.0
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 70m
    memory: 256Mi

configmap:
  data: "version: 1.17.0"
